---

- name: install sshd
  package:
    name: openssh-server
    state: present

- name: configure sshd
  template:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ sshd_cfg }}"
    backup: yes
    validate: sshd -Tf %s
  with_first_found:
    - "{{ playbook_dir }}/templates/{{ sshd_cfg }}.j2"
    - "{{ sshd_cfg }}.j2"
  notify: reload sshd

